apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es
spec:
    version: 8.17.2
    nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false